_homepage:
    pattern:  /
    defaults: { _controller: GameHangmanBundle:Game:index }

GameHangmanBundle:
    resource: "@GameHangmanBundle/Controller/"
    type:     annotation
    prefix:   /game

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
